[package]
name = "rusnel"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
quinn = "0.11.2"
tokio = { version = "1.38.1", features = ["full"] }
rcgen = "0.13.1"
rustls = { version = "0.23.11", features = ["ring"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
serde_json = "1.0.120"
serde = { version = "1.0.*", features = ["derive"] }
anyhow = "1.0.86"
